### ISSUE TITLE
dynamically read properties of vm

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/marvel-virtualmachine#13]
Some properties of the VM, such as #CPUs , RAM, ... can be modified by the user of the VM.
Ideally, the places where these properties are important, would recognize this automatically.

However, for the time being, I think it would be fair to just document where these places are.

**Comment by giovannipizzi** [comment]
Agreed. Anyway, we have to be careful because the # of cpus for torque is set once and for all in the OVA by us, while the number of CPUs while running can be changed afterwards by the user

**Comment by ltalirz** [comment]
I've added some basic documentation of this - what is still missing are instructions of how to modify the torque configuration inside the VM.

**Comment by ltalirz** [comment]
This is now documented, for the moment we won't start reading the properties dynamically.
