### ISSUE TITLE
 add EULA when exporting OVA

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/marvel-virtualmachine#15]
this was written in TODO file

**Comment by ltalirz** [comment]
It seems that with open source licenses like the MIT one [it is not necessary to have an EULA in order to protect oneself as a developer](https://opensource.stackexchange.com/questions/2865/does-open-source-software-need-an-eula-to-protect-the-developer).

I.e. I propose to simply ship the MIT license as the EULA file.

**Comment by ltalirz** [comment]
I just checked and when adding an EULA, virtualbox prompts the user upon importing the image to accept the EULA.
@giovannipizzi just checking that we really need/want this to happen.

**Comment by giovannipizzi** [comment]
Indeed, probably we don't need it (even if MIT only covers the Ansible scripts, not the vm). However, maybe this could be a good place to mention sponsors/funding? Anyway, if you think it's better, ok to remove it for the next release.

**Comment by ltalirz** [comment]
I thought a little more about it and I agree that it is a good place to mention the funding.

Furthermore, since most people will never see the MIT license in the github repo, it is a good place to rid us of any liability (the last paragraph of the MIT) plus mention that the software inside the VM are subject to their respective licenses.

527352ecaf1c621ce0e79dc7f7e1f5b4216d4e66 adds the EULA, the wording (including the mention of the funding) will be adjusted when we make the release.
