### ISSUE TITLE
Example folder rename, more visible, or written in release notes that something can be found there.

### ISSUE THREAD

**Issue by broeder-j** [marvel-nccr/marvel-virtualmachine#23]
The example folder should be more visible (move to the Desktop or rename in tutorial), also write something in the release notes. Took me 10 sec to find, but a usual user might need longer or not find it at all, if he does not expect something to be there in the first place.

**Comment by ltalirz** [comment]
Thanks for the feedback.
Once the example folder actually contains something we will definitely mention it in the release notes (I wasn't sure what to put there so far).

One could move it to the desktop as well. Should people then also be able to double-click on the python files to run the examples? Perhaps...
@giovannipizzi What do you think?

**Comment by giovannipizzi** [comment]
Is it a single folder? Let's put a symlink on the desktop to that, with a simple README inside it to explain what to do (if a text README is not enough we can think to something more, like html render, or a link to a webpage)

**Comment by ltalirz** [comment]
I'm going for a README at this stage.
Fixed in 67ffa1fa2e5620ea93e48f42128ec5cf7e931025
