### ISSUE TITLE
(Minor) Reading from cif and storing, multi structures, loss of Prov

### ISSUE THREAD

**Issue by broeder-j** [marvel-nccr/marvel-virtualmachine#24]
The way the cif file is read (structureData produced from it), looses the provenance of where the structure comes from and not every example should store its own structure…. but instead use a preinstalled one in the db.

**Comment by ltalirz** [comment]
That is a very good point.
As soon as I know exactly which the two structures are going to be, I will pre-load them in aiida.

**Comment by ltalirz** [comment]
This is now taken into consideration in
https://github.com/aiidateam/aiida-max-examples
