### ISSUE TITLE
shared folder file-permissions

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/marvel-virtualmachine#25]
when mounting a shared folder inside the VM, the user doesn't have write permissions (only via sudo).

I tried solution 2 suggested [here](https://stackoverflow.com/a/26981786/1069467) but it didn't solve the problem. Will have to investigate further.

reporter: Mohamad

**Comment by ltalirz** [comment]
I just reproduced the problem (and indeed, just adding the `vagrant` user to the `vboxsf` group does not solve it).

One possible solution is to mount the shared folder as the vagrant user:
`sudo mount -t vboxsf -o uid=1000,gid=1000 <vbox-folder-name> /path/to/folder/on/vm`

@SeyedMohamadMoosavi How did you add the shared folder? Did you have to use a command like the one above (with out `-o ...`) or was it somehow mounted automatically?

**Comment by SeyedMohamadMoosavi** [comment]
I am using this command for mounting the shared folder:
``
sudo mount -t vboxsf VM_shared /home/vagrant/shared/
``
which VM_shared is the name of the shared folder in the shared folder list of the virtual machine.

**Comment by ltalirz** [comment]
Ok, so for the moment, the solution is to use the slightly more elaborate command provided above. a990c70c182bfb28fc1ea49a867278d73969e157 adds this in the release notes and already creates the mount point.
