### ISSUE TITLE
aiida daemon not started

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/marvel-virtualmachine#27]
Sometimes (not reproducible), the aiida daemon is not started properly and one is left in the following state:

```
(aiida) vagrant@marvelvm:~$ verdi daemon status
# Most recent daemon timestamp:0h:18m:50s ago
Could not reach the daemon, I got a socket.error: 
  -> [Errno 111] Connection refused
You can try to stop the daemon and start it again.
```

Re-running the task that restarts the daemon can fix this.
Depositing this here in case it pops up again.

**Comment by ltalirz** [comment]
Ok, this is the state one ends up in for a hard shutdown of the VM and restarting again.
@giovannipizzi Should we start the aiida daemon at startup and what is the best way of doing this?

**Comment by giovannipizzi** [comment]
Mmm.. not sure. As it is a user process, I don't know if it's a good idea to fully automate this.
I would skip this for this VM version, and think to a solution for the next one.
(In case, one can add one line to either the motd or the Release notes to remind people that the daemon needs to be started).
