### ISSUE TITLE
Yambo compilation on VM needs  support for new qexsd format

### ISSUE THREAD

**Issue by mikeatm** [marvel-nccr/marvel-virtualmachine#34]
Yambo (4.2.0) on the VM does not work with QE (6.2) since  it was not compiled with  support for the QEXSD format in newer versions of  QE (>6.x).  Please recompile yambo , taking care to request  this support explicitly at configuration time.  This  configure flag will not be necessary in future releases of yambo though.   The flag is  `--with-p2y-version=qexsd`

**Comment by ltalirz** [comment]
@mikeatm thanks for reporting this and for providing the fix.
I'll let you know once I have the next release candidate ready for download.

**Comment by ltalirz** [comment]
@mikeatm Just checking - for yambo 4.4 we no longer need this flag, correct?
