### ISSUE TITLE
fix /etc/hosts file

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/marvel-virtualmachine#4]
add instructions in /etc/network/if-up.d to update the the /etc/hosts file with the correct IP as required by PBS

**Comment by ltalirz** [comment]
@giovannipizzi 
I'm a bit confused about the use of 127.0.0.1 and 127.0.1.1 here
https://github.com/marvel-nccr/marvel-virtualmachine/blob/61e2cc246d5700da68a414e4827c0be0eaec1b9c/roles/common/tasks/hostname.yml#L13

Do we need both addresses? Or is this a typo?
Anyhow, this is the reason why we currently have two similar lines in /etc/hosts

**Comment by giovannipizzi** [comment]
The typo is in the name. I'm cleaning the lines with 127.0.1.1 - both 127.0.1.1 and 127.0.0.1 are inserted by Ubuntu

**Comment by ltalirz** [comment]
just checked that IP 10.0.2.15 stays the same when
 * importing the .ova on a windows host
 * importing two vms in the same virtualbox installation (both machines will have 10.0.2.15), which is perhaps not ideal...

**Comment by ltalirz** [comment]
fixed in d71c1480d86e0b28e3815f3d93c701e93218d7b5
