### ISSUE TITLE
Document how to make the interface fast

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/marvel-virtualmachine#8]
My experience:
- need to upgrade the VirtualBox Guest Additions to the right version (we do it in Ansible, but most probably the user has a different VirtualBox version)
- on my Mac (Mac Book Pro 2017, Retina display) I need to shutdown the machine, go in the Machine settings, Display tab, and activate 3D acceleration
After this, both mouse and keyboard interaction are reasonably real-time

**Comment by giovannipizzi** [comment]
(By default instead VirtualBox might be a bit slow)

**Comment by ltalirz** [comment]
Fixed in 5521bd6544963b8c17024b2da2a4c7fa4562f03d
