### ISSUE TITLE
decide where to host the vm images

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/marvel-virtualmachine#9]

**Comment by giovannipizzi** [comment]
I think on Materials Cloud, with OVAs stored on a specific container on Swift.
I think in the Work section we should add two new 'buttons' (after the first release), one for the OVAs and similar material, and one for the AiiDA registry (e.g. to search interactively, etc.).
For the moment we can just put it on the object store and put a link from the main websites like aiida.net, marvel-nccr.ch, ...

**Comment by ltalirz** [comment]
VM images will be hosted on CSCS object store.
For links / ads see #30.
